{"uuid": "81279a2f-795d-4a75-9de2-6be593e0c3fe", "children": ["0aece252-f0cc-417a-9fdb-78f3d114d7e8"], "befores": [{"name": "create_user", "status": "failed", "statusDetails": {"message": "AssertionError: User creation failed\nassert False\n", "trace": "  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\tests\\conftest.py\", line 23, in create_user\n    assert False, \"User creation failed\"\n"}, "start": 1723391592888, "stop": 1723391593213}], "start": 1723391592888, "stop": 1723391593295}