{"uuid": "9592f63a-a0d9-44a4-a9e9-37199e7e5ba1", "children": ["15d29c1b-20f7-4b11-a88b-a56a4427b75d"], "befores": [{"name": "create_user", "status": "failed", "statusDetails": {"message": "AssertionError: User creation failed\nassert False\n", "trace": "  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\Diplom_2\\tests\\conftest.py\", line 19, in create_user\n    assert False, \"User creation failed\"\n"}, "start": 1723386794993, "stop": 1723386795297}], "start": 1723386794992, "stop": 1723386795402}