{"uid":"1b336d43b550fa66","name":"Create order with invalid ingredient hash","fullName":"tests.test_create_order.TestCreateOrder#test_create_order_with_invalid_ingredient_hash","historyId":"70b892f8b0761e734d89f7532bbf49e8","time":{"start":1723391592887,"stop":1723391592887,"duration":0},"description":"This test verifies that an order creation attempt with an invalid ingredient hash returns a 500 Internal Server Error.","descriptionHtml":"<p>This test verifies that an order creation attempt with an invalid ingredient hash returns a 500 Internal Server Error.</p>\n","status":"failed","statusMessage":"AssertionError: User creation failed\nassert False","statusTrace":"@pytest.fixture\n    def create_user():\n        payload = User.register_new_user()\n    \n        requests.delete(config.DELETE_USER_PATH, json=payload)\n    \n        response = requests.post(config.CREATE_USER_PATH, json=payload)\n    \n        if response.status_code != 200:\n            print(f\"User creation failed with status code {response.status_code}\")\n            print(f\"Response body: {response.json()}\")\n>           assert False, \"User creation failed\"\nE           AssertionError: User creation failed\nE           assert False\n\ntests\\conftest.py:23: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1723391586345,"stop":1723391586390,"duration":45},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"hasContent":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0},{"name":"create_user","time":{"start":1723391592888,"stop":1723391593213,"duration":325},"status":"failed","statusMessage":"AssertionError: User creation failed\nassert False\n","statusTrace":"  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\Diplom_2\\tests\\conftest.py\", line 23, in create_user\n    assert False, \"User creation failed\"\n","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"hasContent":true,"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0},{"name":"login_user","time":{"start":1723391596461,"stop":1723391596724,"duration":263},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"hasContent":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0}],"testStage":{"description":"This test verifies that an order creation attempt with an invalid ingredient hash returns a 500 Internal Server Error.","status":"failed","statusMessage":"AssertionError: User creation failed\nassert False","statusTrace":"@pytest.fixture\n    def create_user():\n        payload = User.register_new_user()\n    \n        requests.delete(config.DELETE_USER_PATH, json=payload)\n    \n        response = requests.post(config.CREATE_USER_PATH, json=payload)\n    \n        if response.status_code != 200:\n            print(f\"User creation failed with status code {response.status_code}\")\n            print(f\"Response body: {response.json()}\")\n>           assert False, \"User creation failed\"\nE           AssertionError: User creation failed\nE           assert False\n\ntests\\conftest.py:23: AssertionError","steps":[],"attachments":[{"uid":"2504d21400fc8189","name":"stdout","source":"2504d21400fc8189.txt","type":"text/plain","size":110}],"parameters":[],"attachmentStep":false,"hasContent":true,"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1},"afterStages":[],"labels":[{"name":"suite","value":"Order Creation Tests"},{"name":"parentSuite","value":"tests"},{"name":"subSuite","value":"TestCreateOrder"},{"name":"host","value":"DESKTOP-OODMP73"},{"name":"thread","value":"6128-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_create_order"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"1b336d43b550fa66.json","parameterValues":[]}